version: "2"

linters:
    default: standard
    exclusions:
        warn-unused: false
        generated: strict

formatters:
    enable:
        - gofmt
        - golines
    exclusions:
        warn-unused: false
        generated: strict

issues:
    max-issues-per-linter: 50
    max-same-issues: 3
    new: false
    fix: false
    uniq-by-line: true
    whole-files: false
