// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package repository

import (
	"context"
	"time"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO
  user_blocks (user_id, user_email, blocked_by, reason)
VALUES
  ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET
  user_email = EXCLUDED.user_email,
  blocked_by = EXCLUDED.blocked_by,
  reason = EXCLUDED.reason,
  unblocked_by = NULL,
  unblocked_at = NULL
`

type BlockUserParams struct {
	UserID    string  `json:"userId"`
	UserEmail *string `json:"userEmail"`
	BlockedBy string  `json:"blockedBy"`
	Reason    *string `json:"reason"`
}

// BlockUser
//
//	INSERT INTO
//	  user_blocks (user_id, user_email, blocked_by, reason)
//	VALUES
//	  ($1, $2, $3, $4)
//	ON CONFLICT (user_id) DO UPDATE
//	SET
//	  user_email = EXCLUDED.user_email,
//	  blocked_by = EXCLUDED.blocked_by,
//	  reason = EXCLUDED.reason,
//	  unblocked_by = NULL,
//	  unblocked_at = NULL
func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser,
		arg.UserID,
		arg.UserEmail,
		arg.BlockedBy,
		arg.Reason,
	)
	return err
}

const deleteAllUserURLs = `-- name: DeleteAllUserURLs :many
DELETE FROM urls
WHERE
  user_id = $1::text
RETURNING
  id
`

// DeleteAllUserURLs
//
//	DELETE FROM urls
//	WHERE
//	  user_id = $1::text
//	RETURNING
//	  id
func (q *Queries) DeleteAllUserURLs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteAllUserURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteURL = `-- name: DeleteURL :execrows
DELETE FROM urls
WHERE
  id = $1
`

// DeleteURL
//
//	DELETE FROM urls
//	WHERE
//	  id = $1
func (q *Queries) DeleteURL(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteURL, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getURLs = `-- name: GetURLs :many
SELECT
  id,
  long_url,
  created_at,
  is_custom,
  user_id,
  COUNT(*) OVER () as total_count
FROM
  urls
WHERE
  (
    $1::boolean IS NULL
    OR is_custom = $1::boolean
  )
  AND (
    $2::text IS NULL
    OR user_id = $2::text
  )
ORDER BY
  created_at DESC
LIMIT
  $4
OFFSET
  $3
`

type GetURLsParams struct {
	IsCustom *bool   `json:"isCustom"`
	UserID   *string `json:"userId"`
	Offset   int32   `json:"offset"`
	Limit    int32   `json:"limit"`
}

type GetURLsRow struct {
	ID         string    `json:"id"`
	LongUrl    string    `json:"longUrl"`
	CreatedAt  time.Time `json:"createdAt"`
	IsCustom   bool      `json:"isCustom"`
	UserID     *string   `json:"userId"`
	TotalCount int64     `json:"totalCount"`
}

// GetURLs
//
//	SELECT
//	  id,
//	  long_url,
//	  created_at,
//	  is_custom,
//	  user_id,
//	  COUNT(*) OVER () as total_count
//	FROM
//	  urls
//	WHERE
//	  (
//	    $1::boolean IS NULL
//	    OR is_custom = $1::boolean
//	  )
//	  AND (
//	    $2::text IS NULL
//	    OR user_id = $2::text
//	  )
//	ORDER BY
//	  created_at DESC
//	LIMIT
//	  $4
//	OFFSET
//	  $3
func (q *Queries) GetURLs(ctx context.Context, arg GetURLsParams) ([]GetURLsRow, error) {
	rows, err := q.db.Query(ctx, getURLs,
		arg.IsCustom,
		arg.UserID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetURLsRow{}
	for rows.Next() {
		var i GetURLsRow
		if err := rows.Scan(
			&i.ID,
			&i.LongUrl,
			&i.CreatedAt,
			&i.IsCustom,
			&i.UserID,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :exec
UPDATE user_blocks
SET
  unblocked_by = $1::text,
  unblocked_at = NOW()
WHERE
  user_id = $2
`

type UnblockUserParams struct {
	UnblockedBy string `json:"unblockedBy"`
	UserID      string `json:"userId"`
}

// UnblockUser
//
//	UPDATE user_blocks
//	SET
//	  unblocked_by = $1::text,
//	  unblocked_at = NOW()
//	WHERE
//	  user_id = $2
func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.UnblockedBy, arg.UserID)
	return err
}
