// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        string             `json:"id"`
	LongUrl   string             `json:"longUrl"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
