// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        string    `json:"id"`
	LongUrl   string    `json:"longUrl"`
	CreatedAt time.Time `json:"createdAt"`
	IsCustom  bool      `json:"isCustom"`
	UserID    *string   `json:"userId"`
}

type UserBlock struct {
	ID          int32              `json:"id"`
	UserID      string             `json:"userId"`
	UserEmail   *string            `json:"userEmail"`
	BlockedBy   string             `json:"blockedBy"`
	BlockedAt   time.Time          `json:"blockedAt"`
	UnblockedBy *string            `json:"unblockedBy"`
	UnblockedAt pgtype.Timestamptz `json:"unblockedAt"`
	Reason      *string            `json:"reason"`
}
