// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type Url struct {
	ID        string    `json:"id"`
	LongUrl   string    `json:"longUrl"`
	CreatedAt time.Time `json:"createdAt"`
	IsCustom  bool      `json:"isCustom"`
}
