// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package repository

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO
  urls (id, long_url, is_custom)
VALUES
  ($1, $2, $3)
RETURNING
  id, long_url, created_at, is_custom, user_id
`

type CreateUrlParams struct {
	ID       string `json:"id"`
	LongUrl  string `json:"longUrl"`
	IsCustom bool   `json:"isCustom"`
}

// CreateUrl
//
//	INSERT INTO
//	  urls (id, long_url, is_custom)
//	VALUES
//	  ($1, $2, $3)
//	RETURNING
//	  id, long_url, created_at, is_custom, user_id
func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl, arg.ID, arg.LongUrl, arg.IsCustom)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.CreatedAt,
		&i.IsCustom,
		&i.UserID,
	)
	return i, err
}

const deleteUrl = `-- name: DeleteUrl :execrows
DELETE FROM urls
WHERE
  id = $1
`

// DeleteUrl
//
//	DELETE FROM urls
//	WHERE
//	  id = $1
func (q *Queries) DeleteUrl(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUrl, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLongUrl = `-- name: GetLongUrl :one
SELECT
  long_url
FROM
  urls
WHERE
  id = $1
LIMIT
  1
`

// GetLongUrl
//
//	SELECT
//	  long_url
//	FROM
//	  urls
//	WHERE
//	  id = $1
//	LIMIT
//	  1
func (q *Queries) GetLongUrl(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getLongUrl, id)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}
