// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: urls.sql

package repository

import (
	"context"
)

const getLongUrl = `-- name: GetLongUrl :one
SELECT long_url
  FROM urls
 WHERE id = $1
 LIMIT 1
`

// GetLongUrl
//
//	SELECT long_url
//	  FROM urls
//	 WHERE id = $1
//	 LIMIT 1
func (q *Queries) GetLongUrl(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getLongUrl, id)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}
