name: lint
on:
    pull_request:

jobs:
    golangci:
        runs-on: ubuntu-latest
        name: golangci-lint
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24.x"

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v8
              with:
                  version: v2.1

    govulncheck:
        runs-on: ubuntu-latest
        name: govulncheck
        steps:
            - id: govulncheck
              uses: golang/govulncheck-action@v1
              with:
                  go-version-input: 1.24.x
                  go-package: ./...
